global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-collector'
    #scrape_interval: 5s  # Intervall speziell für den OTel Collector
    static_configs:
      - targets: ['node-collector:9464'] # Der Host und Port des OTel Collectors für Metriken

